config/routes.rb
Rails.application.routes.draw do

 
   root 'users#index'

   get 'logout', to: 'sessions#destroy', as: 'logout'

   post '/users/login', to: 'users#login'
   
   resources :deals
   post '/deals/:id', to: 'deals#update'

   post '/users/create_friend', to: 'users#create_friend'

   resources :users

   resources :sessions

end

app/models/deal.rb
class Deal < ActiveRecord::Base
  validates :amount, presence: true
  validates :payer, presence: true
  validates :receiver, presence: true

  belongs_to :payer, class_name: "User", foreign_key: "payer_id"
  belongs_to :receiver, class_name: "User", foreign_key: "receiver_id"

  # after_initialize :defaults
  # def defaults
  #   self.description = 'no description yet'
  #   self.settled = 'false'
  # end

  # has_many :settled_deals -> {where settled: true}, class_name: "Deal"
  def self.settled_deals
    self.where(settled: true)
  end
  def self.unsettled_deals
    self.where(settled: false)
  end
  def settle_now
    self.update(settled: true)
  end

  def counterpart(current_user)
    # return the user in the deal who is not current_user
    self.payer == current_user ? self.receiver.name : self.payer.name
  end
  def verb_to_describe(current_user)
    self.payer == current_user ? 'Give' : 'Owe'
  end
  def time_create_readable
    self.created_at.strftime("%d-%b-%Y")
  end
  def long_description(current_user)
    "you #{self.verb_to_describe(current_user)} #{self.counterpart(current_user)}  #{self.amount} - #{self.description}"
  end



end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  validates :password, presence: true, on: :create
  validates :email, presence: true, uniqueness: {case_sensitive: false}


  validates :name, presence: true, length: {minimum: 2}, uniqueness: true
  
  has_many :deals_as_payer, class_name: "Deal", foreign_key: "payer_id"
  has_many :deals_as_receiver, class_name: "Deal", foreign_key: "receiver_id"
  # SELECT "deals".* FROM "deals" WHERE "deals"."payer_id" = $1  [["payer_id", 1]]
  # SELECT "deals".* FROM "deals" WHERE "deals"."receiver_id" = $1  [["receiver_id", 1]]

  def all_deals
    self.deals_as_payer + self.deals_as_receiver
  end

  def to_receive
    self.deals_as_payer.select {|deal| deal.settled == 'false'}.map(&:amount).inject(&:+) || 0
  end
  def to_pay
    self.deals_as_receiver.select {|deal| deal.settled == 'false'}.map(&:amount).inject(&:+) || 0
  end

  def recap_balance(other_user)
    pay = self.deals_as_payer.unsettled_deals.where(receiver: other_user).map(&:amount).inject(&:+) || 0
    receive = self.deals_as_receiver.unsettled_deals.where(payer: other_user).map(&:amount).inject(&:+) || 0
    receive - pay
    # negative number means self owes ££ to other user (because means he is more payer than receiver)
  end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session


  helper_method :current_user
  # helper method means we can use it in the view !
  private
  def current_user
    begin
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue ActiveRecord::RecordNotFound
      session[:user_id] = nil
    end
  end
  
 

end

app/controllers/deals_controller.rb
class DealsController < ApplicationController

  def index
    @deal = Deal.new 
    @user = User.new 
    @users = User.all 

#  Here iI MUST keep 'true' 'false', not true/false
    @pending = current_user.all_deals.select {|deal| deal.settled == 'false'}.sort_by(&:updated_at).reverse
    # binding.pry
    @history = current_user.all_deals.select {|deal| deal.settled == 't'}.sort_by(&:created_at).reverse

    @deals_to_pay = @pending.select {|deal| deal.receiver == current_user }.sort_by(&:amount).reverse
    @deals_to_receive = @pending.select {|deal| deal.payer == current_user }.sort_by(&:amount).reverse
  end

  def create

    if params[:payer]
      payer = User.find(params[:payer].to_i)
      receiver = User.find(params[:receiver].to_i)
      amount = params[:amount].to_i
      description = params[:description]
    elsif params[:deal]
      payer = User.find(params[:deal][:payer].to_i)
      receiver = User.find(params[:deal][:receiver].to_i)
      amount = params[:deal][:amount].to_i
      description = params[:deal][:description]
    end
        
    @deal = Deal.create amount: amount, payer: payer, receiver: receiver, description: description
    @time = @deal.time_create_readable
    @full_deal = {deal: @deal, time: @time, long_description: @deal.long_description(current_user)}

    respond_to do |format|
      format.html 
      format.json { render json: @full_deal, status: 200 }
    end  
  end

  def update

    @deal = Deal.find params[:id]
    # @deal.settle_now
    @deal.update(params.permit(:amount, :description, :settled))
    @time = @deal.time_create_readable

    @full_deal = {deal: @deal, time: @time, long_description: @deal.long_description(current_user)}

    respond_to do |format|
      format.html { redirect_to deals_path }
      # format.json { redirect_to deals_path }
      format.json { render json: @full_deal, status: 200 }
    end  
  end

  def show
    @deal = Deal.find params[:id] 
    @time = @deal.time_create_readable
    @full_deal = {deal: @deal, time: @time, long_description: @deal.long_description(current_user)}

    respond_to do |format|
      format.html 
      format.json { render json: @full_deal, status: 200 }
    end
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end
 
  def create
    user = User.where(email: params[:email]).first
 
    # if user && user.authenticate(params[:password])
    if user
      session[:user_id] = user.id
      redirect_to deals_path
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end
 
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
      @users = User.all 
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:name, :email, :password, :password_confirmation))
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  def create_friend
    @user = User.create name: params[:name]
    
    respond_to do |format|
      format.html { redirect_to deals_path }
      format.json { render json: @user, status: 200 }
    end    
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/deals/index.html.erb
<header>
  <div id="recaps">
    <div><p>Welome <%= current_user.name %></p></div>
    <div><p>To Pay</div>
    <div><p id='recap_to_pay'><%= current_user.to_pay %></p></div>
    <div><p>To Receive</p></div>
    <div><p id='recap_to_receive'><%= current_user.to_receive %></p></div>
  </div>
</header>

<div id="quick_adds">

  <%= form_for @deal do |form| %>   
    <%= form.submit 'New deal' %>
    <%= form.text_field :amount, placeholder: "$£€¥" %>
    
    <%= form.label "From" %>
    <%= form.select :payer, options_from_collection_for_select(@users, "id", "name", current_user.id) %>
    <%= form.label "To" %>
    <%= form.select :receiver, options_from_collection_for_select(@users, "id", "name", current_user.id) %>

    <%= form.text_field :description %>

    <%= form.submit 'Go!' %>
  <% end %>

<!-- NEED TO RENAME THE FORM ID   because new_uuser is already taken by the login stuffs-->
  <%= form_for @user, :html => { :id => "new_friend" } do |form| %>
    <%= form.submit 'New friend' %>
    <%= form.text_field :name, placeholder: "Friend's name" %>
    <%= form.submit 'Go!' %>
  <% end %>

</div>

<div id="view_zone">

  <div id="quick_menu">
    <ul>
      <li><a href="#" data-go='#pending_deals' class='active_menu'>Pending</a></li>
      <li><a href="#" data-go='#friends'>Friends</a></li>
      <li><a href="#" data-go='#deals_to_pay'>To Pay</a></li>
      <li><a href="#" data-go='#deals_to_receive'>To Receive</a></li>
      <li><a href="#" data-go='#history'>History</a></li>
    </ul>
  </div>
  
  <div id="left_column" class='column'>

    <div id="pending_deals" class="sub_zone js_sub_zone">
      <h4 class='active_menu'>Gotta take care of these bad boys.</h4>

      <% @pending.each do |deal| %>
      <ul class='indiv_deal_box'>
        <li class="indiv_deal_details"> <span><%= "#{deal.time_create_readable}" %> - </span> <%= link_to "#{deal.long_description(current_user)}", '#', data: {deal_id: "#{deal.id}"} %></li>

        <% if deal.payer.name != current_user.name  %>
          <li class='indiv_deal_pay'><button class="pay_button" data-id=<%= deal.id %>>Pay</button></li>
        <% end %>
      </ul>
      <% end %>
    </div>

    <div id="history" class="sub_zone js_sub_zone hidden">
      <h4 class='active_menu'>Things of the past.</h4>

      <% @history.each do |deal| %>
      <ul class='indiv_deal_box'>
        <li class="indiv_deal_details"> <span><%= "#{deal.time_create_readable}" %> - </span> <%= link_to "#{deal.long_description(current_user)}", '#', data: {deal_id: "#{deal.id}"} %></li>
      </ul>
      <% end %>
    </div>

    <div id="friends" class="sub_zone js_sub_zone hidden">
      <h4 class='active_menu'>Good fences make good neighbors.</h4>
    </div>

    <div id="deals_to_pay" class="sub_zone js_sub_zone hidden">
      <h4 class='active_menu'>A Lannister always pays his debts.</h4>

      <% @deals_to_pay.each do |deal| %>
      <ul class='indiv_deal_box'>
        <li class="indiv_deal_details"> <span><%= "#{deal.time_create_readable}" %> - </span> <%= link_to "#{deal.long_description(current_user)}", '#', data: {deal_id: "#{deal.id}"} %></li>
        <li class='indiv_deal_pay'><button class="pay_button" data-id=<%= deal.id %>>Pay</button></li>
      </ul>
      <% end %>
    </div>

      <div id="deals_to_receive" class="sub_zone js_sub_zone hidden">
      <h4 class='active_menu'>If you owe your bank a hundred pounds, you have a problem.<br> But if you owe a million, it has.</h4>

      <% @deals_to_receive.each do |deal| %>
      <ul class='indiv_deal_box'>
        <li class="indiv_deal_details"> <span><%= "#{deal.time_create_readable}" %> - </span> <%= link_to "#{deal.long_description(current_user)}", '#', data: {deal_id: "#{deal.id}"} %></li>
      </ul>
      <% end %>
    </div>

  </div> <!-- end of LEFT column -->

  <div id="right_column" class="column">
    <div id="edit_zone" class="sub_zone">
      <h4 class='active_menu'>Make some small change.</h4>

      <p class="warning_in_edit come_back">Select a deal to make changes and see the history with your friend</p>

  </div><!-- end of RIGHT column -->

</div> <!-- end of VIEW zone -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>I O U</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="main_container">

<% flash.each do |name, msg| %>
  <div class="flash-message flash-message-<% name %>">
    <%= msg %>
  </div>
<% end %>

<% if current_user %>
  <p id='login_mini_msg' class='warning_in_edit'>Logged in as <%= current_user.name %> | <%= link_to 'Log out', logout_path %></p>
<% else %>
  <p>Please log in</p>
  <p><%= link_to 'log in', new_session_path %></p>
  <p><%= link_to 'sign up', new_user_path %></p>
<% end %>
  
    <%= yield %>

</div>
</body>
</html>

app/views/users/index.html.erb
<ul>>
<% @users.each do |user| %>
<li><%= user.name %></li>
<li><%= user.email %></li>
<% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>
 
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>